site_name: Computer science

theme:
  name: material
  
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - content.code.copy
    - content.tabs.link
    - navigation.tabs

markdown_extensions:
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.arithmatex:
      generic: true
  - def_list

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Sorting Algorithm:
    - Bubble sort: sorting-algorithm/bubble-sort.md
    - Insertion sort: sorting-algorithm/insertion-sort.md
    - Selection sort: sorting-algorithm/selection-sort.md

  - Machine learning:
      - General notion:
        - Introduction: machine-learning/intro.md
        - Before developing: machine-learning/prerequisites.md
        - Model evaluation: machine-learning/model-evaluation.md
        - Tooling: machine-learning/tooling.md
        - Additional resources: machine-learning/resources.md
        - Parameter tuning: machine-learning/parameter-tuning.md
        - Code snippets : machine-learning/snippets.md
      - Algorithm:
          - Linear regression: machine-learning/linear-regression.md
          - Logistic regression: machine-learning/logistic-regression.md
          - K Nearest neighbor: machine-learning/knn.md
          - Decision tree: machine-learning/decision_tree.md
          - SVM : machine-learning/svm.md
      - Practice:
          - Exercise: machine-learning/exercice.md
          - Exercise 2: machine-learning/exercise-2.md

